import test from"node:test";import assert from"node:assert/strict";import{PortalProjectorHttpError,createPortalProjectorHttpAdapter}from"../src/index.mjs";
const C="a".repeat(40);function f(o={}){const calls=[];const readApi=Object.freeze({mutationAllowed:false,getSnapshot:a=>(calls.push(["snapshot",a]),{sourceCommit:C,contentChecksum:"c".repeat(64)}),getSummary:a=>(calls.push(["summary",a]),{sourceCommit:C,contentChecksum:"c".repeat(64),recordCount:2}),listRecords:a=>(calls.push(["records",a]),{items:[],page:{}}),getRecord:a=>(calls.push(["record",a]),a.institutionalId==="missing"?null:a),listVersions:a=>(calls.push(["versions",a]),{items:[],page:{}})});return{calls,adapter:createPortalProjectorHttpAdapter({readApi,authenticate:o.authenticate??(async()=>({id:"u"})),authorize:o.authorize??(async()=>true)})}}
test("read only",()=>{const{adapter}=f();assert.equal(adapter.mutationAllowed,false);assert.equal("publish"in adapter,false);assert.equal("listen"in adapter,false)});
test("requires auth adapters",()=>assert.throws(()=>createPortalProjectorHttpAdapter({readApi:{mutationAllowed:false,getSnapshot(){},getSummary(){},listRecords(){},getRecord(){},listVersions(){}}}),e=>e instanceof PortalProjectorHttpError&&e.code==="PORTAL_HTTP_ADAPTER_DEPENDENCY_INVALID"));
test("401",async()=>assert.equal((await f({authenticate:async()=>null}).adapter.handle({method:"GET",path:"/v1/portal/summary"})).status,401));
test("403",async()=>assert.equal((await f({authorize:async()=>false}).adapter.handle({method:"GET",path:"/v1/portal/summary"})).status,403));
test("summary metadata",async()=>{const x=f();const r=await x.adapter.handle({method:"GET",path:`/v1/portal/summary?commit=${C}`});assert.equal(r.status,200);assert.equal(r.headers["x-source-commit"],C);assert.deepEqual(x.calls,[["summary",{commit:C}]])});
test("records pagination",async()=>{const x=f();await x.adapter.handle({method:"GET",path:`/v1/portal/records?institutionalType=Node&offset=1&limit=2&commit=${C}`});assert.deepEqual(x.calls,[["records",{commit:C,institutionalType:"Node",offset:1,limit:2}]])});
test("record and 404",async()=>{const x=f();assert.equal((await x.adapter.handle({method:"GET",path:"/v1/portal/records/Node/NODE-1"})).status,200);assert.equal((await x.adapter.handle({method:"GET",path:"/v1/portal/records/Node/missing"})).status,404)});
test("405 before auth",async()=>{let n=0;const x=f({authenticate:async()=>{n++;return{}}});const r=await x.adapter.handle({method:"POST",path:"/v1/portal/summary"});assert.equal(r.status,405);assert.equal(n,0)});
test("invalid query",async()=>assert.equal((await f().adapter.handle({method:"GET",path:"/v1/portal/records?limit=1&limit=2"})).status,400));
test("hides secrets",async()=>{const api={mutationAllowed:false,getSnapshot(){throw Error("DATABASE_URL=secret")},getSummary(){throw Error("DATABASE_URL=secret")},listRecords(){throw Error("DATABASE_URL=secret")},getRecord(){throw Error("DATABASE_URL=secret")},listVersions(){throw Error("DATABASE_URL=secret")}};const a=createPortalProjectorHttpAdapter({readApi:api,authenticate:async()=>({}),authorize:async()=>true});const r=await a.handle({method:"GET",path:"/v1/portal/summary"});assert.equal(r.status,500);assert.equal(JSON.stringify(r).includes("secret"),false)});
test("outside path 404",async()=>assert.equal((await f().adapter.handle({method:"GET",path:"/v1/other"})).status,404));
