
import assert from "node:assert/strict";
import test from "node:test";
import {SubscriptionDomainError,createMemorySubscriptionRepository,createSubscriptionService,createSubscriptionSnapshot} from "../src/index.mjs";
const T0="2026-07-20T00:00:00.000Z",T1="2026-08-20T00:00:00.000Z",T2="2026-09-20T00:00:00.000Z";
const product=(x={})=>({id:"platform-core",version:1,status:"READY_TO_SELL",planIds:["developer","team"],...x});
const plan=(x={})=>({id:"developer",version:1,productId:"platform-core",status:"ACTIVE",...x});
const svc=()=>{let n=0,t=0;return createSubscriptionService({idFactory:()=>`snap-${++n}`,clock:()=>new Date(Date.parse(T0)+t++*1000).toISOString(),assertTenantOperational:id=>{if(id==="blocked")throw new SubscriptionDomainError("tenant_not_operational","blocked")}})};
const create=(s,x={})=>s.createPending({subscriptionId:"sub-1",tenantId:"tenant-1",product:product(),plan:plan(),sourceEventId:"checkout-1",currentPeriodStart:T0,currentPeriodEnd:T1,...x});
const activate=s=>{create(s);return s.activate({subscriptionId:"sub-1",sourceEventId:"payment-1",activatedAt:T0})};

test("creates immutable pending snapshots and validates catalog",()=>{const s=createSubscriptionSnapshot({snapshotId:"s1",subscriptionId:"sub-1",revision:1,tenantId:"tenant-1",productId:"platform-core",productVersion:1,planId:"developer",planVersion:1,status:"pending",billingInterval:"month",billingAnchor:T0,currentPeriodStart:T0,currentPeriodEnd:T1,startedAt:null,endedAt:null,cancelAtPeriodEnd:false,pendingChange:null,sourceEventId:"e1",previousSnapshotId:null,createdAt:T0,metadata:{a:{b:1}}});assert.throws(()=>{s.metadata.a.b=2},TypeError);assert.throws(()=>create(svc(),{product:product({status:"SPECIFIED"})}),e=>e.code==="product_not_sellable")});
test("repository is append-only and idempotent",()=>{const r=createMemorySubscriptionRepository(),s=createSubscriptionSnapshot({snapshotId:"s1",subscriptionId:"sub-1",revision:1,tenantId:"tenant-1",productId:"platform-core",productVersion:1,planId:"developer",planVersion:1,status:"pending",billingInterval:"month",billingAnchor:T0,currentPeriodStart:T0,currentPeriodEnd:T1,startedAt:null,endedAt:null,cancelAtPeriodEnd:false,pendingChange:null,sourceEventId:"e1",previousSnapshotId:null,createdAt:T0});assert.equal(r.append(s).appended,true);assert.equal(r.append({...s,snapshotId:"s2"}).appended,false);assert.throws(()=>r.append({...s,snapshotId:"s3",revision:3,sourceEventId:"e3"}),e=>e.code==="invalid_subscription_revision")});
test("creates and activates subscriptions",()=>{const s=svc(),a=activate(s);assert.equal(a.snapshot.status,"active");assert.deepEqual(s.listHistory("sub-1").map(x=>x.status),["pending","active"]);assert.equal(a.events[0].type,"subscription.activated")});
test("deduplicates repeated events",()=>{const s=svc();activate(s);const a=s.markPastDue({subscriptionId:"sub-1",sourceEventId:"overdue-1"}),b=s.markPastDue({subscriptionId:"sub-1",sourceEventId:"overdue-1"});assert.equal(a.appended,true);assert.equal(b.appended,false);assert.deepEqual(b.events,[])});
test("handles past_due suspension and recovery",()=>{const s=svc();activate(s);s.markPastDue({subscriptionId:"sub-1",sourceEventId:"overdue-1"});s.suspend({subscriptionId:"sub-1",sourceEventId:"suspend-1"});const r=s.recover({subscriptionId:"sub-1",sourceEventId:"recover-1"});assert.equal(r.snapshot.status,"active");assert.equal(r.snapshot.planId,"developer")});
test("schedules and applies plan changes when due",()=>{const s=svc();activate(s);s.schedulePlanChange({subscriptionId:"sub-1",product:product(),plan:plan({id:"team",version:2}),sourceEventId:"change-1",effectiveAt:T1});assert.throws(()=>s.applyScheduledPlanChange({subscriptionId:"sub-1",sourceEventId:"early",effectiveAt:"2026-08-19T00:00:00.000Z"}),e=>e.code==="plan_change_not_due");assert.equal(s.applyScheduledPlanChange({subscriptionId:"sub-1",sourceEventId:"apply",effectiveAt:T1}).snapshot.planId,"team")});
test("renews periods and applies due changes atomically",()=>{const s=svc();activate(s);s.schedulePlanChange({subscriptionId:"sub-1",product:product(),plan:plan({id:"team",version:2}),sourceEventId:"change-1",effectiveAt:T1});const r=s.renew({subscriptionId:"sub-1",sourceEventId:"renew-1",currentPeriodStart:T1,currentPeriodEnd:T2});assert.equal(r.snapshot.planId,"team");assert.equal(r.snapshot.currentPeriodEnd,T2);assert.equal(r.events[0].data.planChanged,true)});
test("supports immediate and period-end cancellation",()=>{const a=svc();activate(a);assert.equal(a.cancel({subscriptionId:"sub-1",sourceEventId:"cancel-now",mode:"immediate",effectiveAt:T0}).snapshot.status,"cancelled");const b=svc();activate(b);b.cancel({subscriptionId:"sub-1",sourceEventId:"cancel-later",mode:"period_end"});assert.throws(()=>b.renew({subscriptionId:"sub-1",sourceEventId:"renew",currentPeriodStart:T1,currentPeriodEnd:T2}),e=>e.code==="cancellation_scheduled");assert.equal(b.finalizePeriodEnd({subscriptionId:"sub-1",sourceEventId:"finish",endedAt:T1}).snapshot.status,"cancelled")});
test("expires and blocks terminal mutations",()=>{const s=svc();activate(s);s.expire({subscriptionId:"sub-1",sourceEventId:"expire-1",endedAt:T1});assert.throws(()=>s.suspend({subscriptionId:"sub-1",sourceEventId:"late"}),e=>e.code==="terminal_subscription");assert.deepEqual(s.listCurrentByTenant("tenant-1").map(x=>x.status),["expired"])});
