
import assert from "node:assert/strict";import test from "node:test";
import {createBrowserSessionAuthenticator,hashBrowserSessionSecret} from "../src/browser-session-authenticator.mjs";
import {BIOMETRIC_BROWSER_SESSION_ISSUER_V1 as P,createBiometricBrowserSessionIssuer as create} from "../src/biometric-browser-session-issuer-v1.mjs";
const D=c=>`sha256:${c.repeat(64)}`;
const decision=(z={})=>({version:"trust-biometric-login-decision/v1",mode:"sandbox-conformance",status:"authorized",authentication:{method:"trust_biometric_face_sandbox",modality:"face",verificationId:"v1",providerId:"trust-face-sandbox",policyId:"bp1",policyDigest:D("a"),policyProductionValidated:false},identity:{role:"client",principal:{id:"p1",tenantId:"t1",status:"active",scopes:["product:read"],authenticationMethod:"trust_biometric_face_sandbox"}},access:{allowed:true,tenantId:"t1",workspaceId:"w1",productId:"prod1",accessGrantId:"g1"},session:{issuanceAllowed:false,issued:false,nextStage:"auth-core-session-issuance"},rawBiometricMaterialForwarded:false,rawBiometricMaterialPersisted:false,productionAuthorized:false,productionReady:false,...z});
function h(over={}){const records=new Map();let persist=0,random=0;const issuer=create({persistSession:over.persistSession|| (async r=>{persist++;records.set(r.secretHash,r);return true}),authorizeSessionIssuance:over.authorizeSessionIssuance|| (async()=>({allowed:true,policyId:"sp1",policyDigest:D("b"),productionValidated:false})),randomBytes:()=>{random++;return Buffer.alloc(32,7)},createSessionId:()=> "session-1",now:()=>new Date("2026-09-03T04:00:00Z"),maxAgeSeconds:900});return {issuer,records,calls:()=>({persist,random})}}
test("profile sandbox",()=>{assert.equal(P.productionEnabled,false);assert.equal(P.sessionSecretPersisted,false)});
test("round trip",async()=>{const x=h(),r=await x.issuer.issue({loginDecision:decision()});assert.equal(r.status,"issued");assert.equal(r.productionReady,false);const pair=r.setCookieHeader.split(";")[0],secret=pair.split("=")[1],stored=x.records.get(hashBrowserSessionSecret(secret));assert.ok(stored);assert.equal(stored.sessionSecret,undefined);const auth=createBrowserSessionAuthenticator({resolveSessionByHash:async q=>x.records.get(q)||null,now:()=>new Date("2026-09-03T04:01:00Z")});const id=await auth.authenticate({cookie:pair});assert.equal(id.principal.id,"p1");assert.equal(id.principal.authenticationMethod,"browser_session")});
test("policy denial before randomness",async()=>{const x=h({authorizeSessionIssuance:async()=>({allowed:false,reason:"step_up"})});await assert.rejects(()=>x.issuer.issue({loginDecision:decision()}),e=>e.code==="session_issuance_denied");assert.deepEqual(x.calls(),{persist:0,random:0})});
test("denied source",async()=>{const x=h();await assert.rejects(()=>x.issuer.issue({loginDecision:decision({status:"denied"})}),e=>e.code==="login_decision_not_authorized")});
test("production source blocked",async()=>{const x=h();await assert.rejects(()=>x.issuer.issue({loginDecision:decision({productionAuthorized:true})}),e=>e.code==="production_not_authorized")});
test("raw material blocked",async()=>{let pc=0;const x=h({authorizeSessionIssuance:async()=>{pc++;return {allowed:true,policyId:"p",policyDigest:D("c"),productionValidated:false}}});await assert.rejects(()=>x.issuer.issue({loginDecision:decision({rawImage:"x"})}),e=>e.code==="sensitive_material_forbidden");assert.equal(pc,0)});
test("tenant mismatch blocked",async()=>{const x=h(),d=decision();d.access={...d.access,tenantId:"t2"};await assert.rejects(()=>x.issuer.issue({loginDecision:d}),e=>e.code==="tenant_mismatch")});
test("invalid handoff blocked",async()=>{const x=h(),d=decision();d.session={...d.session,nextStage:"other"};await assert.rejects(()=>x.isssuer.issue({loginDecision:d}),e=>e.code==="invalid_session_handoff")});
test("production policy blocked",async()=>{const x=h({authorizeSessionIssuance:async()=>({allowed:true,policyId:"p",policyDigest:D("c"),productionValidated:true})});await assert.rejects(()=>x.issuer.issue({loginDecision:decision()}),e=>e.code==="production_not_authorized")});
test("persistence fail",async()=>{let rec;const x=h({persistSession:async r=>{rec=r;return false}});await assert.rejects(()=>x.issuer.issue({loginDecision:decision()}),e=>e.code==="session_persistence_failed");assert.equal(rec.sessionSecret,undefined)});
