import assert from "node:assert/strict";
import test from "node:test";
import { createConsentedRealEvaluationAuthorization } from "../src/consented-real-eval-auth-gate-v1.mjs";
import { TRUST_FACE_EXTERNAL_LIVENESS_PAD_PROVIDER_BOUNDARY_V1 as P, createExternalLivenessPadProviderBoundary as create } from "../src/external-liveness-pad-provider-boundary-v1.mjs";
const D=c=>`sha256:${c.repeat(64)}`;
const A=(o={})=>createConsentedRealEvaluationAuthorization({authorizationId:"a1",scope:"face-1to1-evaluation",protocolDigest:D("7"),codeCommit:"pad-code-1",issuedAt:"2026-09-02T15:00:00Z",expiresAt:"2026-09-02T17:00:00Z",evaluationOnly:true,trainingAuthorized:false,realBiometricEvaluationAuthorized:true,...o});
function Q(o={}){return {providerId:"p1",providerVersion:"v1",codeCommit:"pad-code-1",modelDigest:D("1"),evaluationDigest:D("2"),inputModality:"video",calls:0,async evaluateByRef(){this.calls++;return {presentationAttackDetected:false,padScore:.91,livenessScore:.89}},...o};}
test("profile remains non-production",()=>{for(const k of ["rawImagePayloadAccepted","rawVideoPayloadAccepted","binaryPayloadAccepted","providerResultStored","activeChallengeExecutedByBoundary","originAttestedByBoundary","providerAuthenticityVerified","externalIndependentValidationVerified","realPadReady","benchmarkReady","productionReady","biometricClaimReady"])assert.equal(P[k],false)});
test("sensitive provider config rejected",()=>{const p=Q({privateKey:"x"});assert.throws(()=>create({provider:p,protocolDigest:D("7")}),e=>e.code==="external_pad_provider_sensitive_payload_forbidden");assert.equal(p.calls,0)});
test("invalid modality rejected",()=>assert.throws(()=>create({provider:Q({inputModality:"depth"}),protocolDigest:D("7")}),e=>e.code==="external_pad_provider_invalid_modality"));
test("expired auth before provider",async()=>{const p=Q(),b=create({provider:p,protocolDigest:D("7")});await assert.rejects(()=>b.evaluateByRef({sampleRef:"sample://1",authorization:A({expiresAt:"2026-09-02T15:30:00Z"}),now:"2026-09-02T16:00:00Z"}),e=>e.code==="authorization_not_active");assert.equal(p.calls,0)});
test("authorized result remains candidate-only",async()=>{const p=Q(),b=create({provider:p,protocolDigest:D("7")}),r=await b.evaluateByRef({sampleRef:"sample://1",authorization:A(),now:"2026-09-02T16:00:00Z"});assert.equal(p.calls,1);assert.equal(r.padScore,.91);assert.equal(r.livenessScore,.89);assert.equal(r.presentationAttackDetected,false);assert.equal(r.realPadReady,false);assert.equal(r.productionReady,false)});
test("invalid score rejected",async()=>{const b=create({provider:Q({async evaluateByRef(){return {presentationAttackDetected:false,padScore:1.2,livenessScore:.9}}}),protocolDigest:D("7")});await assert.rejects(()=>b.evaluateByRef({sampleRef:"sample://2",authorization:A(),now:"2026-09-02T16:00:00Z"}),e=>e.code==="external_pad_provider_invalid_score")});
test("invalid attack flag rejected",async()=>{const b=create({provider:Q({async evaluateByRef(){return {presentationAttackDetected:"no",padScore:.9,livenessScore:.9}}}),protocolDigest:D("7")});await assert.rejects(()=>b.evaluateByRef({sampleRef:"sample://3",authorization:A(),now:"2026-09-02T16:00:00Z"}),e=>e.code==="external_pad_provider_invalid_result")});
test("inline/raw media rejected",async()=>{const p=Q(),b=create({provider:p,protocolDigest:D("7")});await assert.rejects(()=>b.evaluateByRef({sampleRef:"data:video/mp4;base64,x",authorization:A(),now:"2026-09-02T16:00:00Z"}),e=>e.code==="external_pad_provider_inline_payload_forbidden");await assert.rejects(()=>b.evaluateByRef({sampleRef:"sample://4",authorization:{...A(),rawVideo:"x"},now:"2026-09-02T16:00:00Z"}),e=>e.code==="external_pad_provider_sensitive_payload_forbidden");assert.equal(p.calls,0)});
test("no production management surface",()=>{const b=create({provider:Q(),protocolDigest:D("7")});for(const k of ["deploy","publish","train","loadModelWeights","storePrivateKey","writeVault","deleteTemplate","storeMedia"])assert.equal(b[k],undefined)});
