const H={"content-type":"application/json; charset=utf-8","cache-control":"private, no-store"};
export class PortalProjectorHttpError extends Error{constructor(code,message,details={}){super(message);this.name="PortalProjectorHttpError";this.code=code;this.details=structuredClone(details)}}
const fail=(c,m,d={})=>{throw new PortalProjectorHttpError(c,m,d)};
const fn=(v,n)=>{if(typeof v!=="function")fail("PORTAL_HTTP_ADAPTER_DEPENDENCY_INVALID",`${n} must be a function`)};
function checkApi(api){if(!api||api.mutationAllowed!==false)fail("PORTAL_HTTP_ADAPTER_READ_API_INVALID","readApi must be read-only");for(const n of["getSnapshot","getSummary","listRecords","getRecord","listVersions"])fn(api[n],`readApi.${n}`);if("publish"in api||"publisher"in api||"write"in api)fail("PORTAL_HTTP_ADAPTER_READ_API_INVALID","mutation capability exposed")}
const res=(status,body,headers={})=>Object.freeze({status,headers:Object.freeze({...H,...headers}),body:structuredClone(body)});
const err=(s,c,m,h={})=>res(s,{error:{code:c,message:m}},h);
function one(q,n){const a=q.getAll(n);if(a.length>1)fail("PORTAL_HTTP_ADAPTER_QUERY_INVALID",`${n} duplicated`);const v=a[0]?.trim();return v||undefined}
function integer(q,n){const v=one(q,n);if(v===undefined)return undefined;if(!/^\d+$/.test(v))fail("PORTAL_HTTP_ADAPTER_QUERY_INVALID",`${n} invalid`);return Number(v)}
function seg(v){try{const x=decodeURIComponent(v);if(!x||x.includes("/")||x.includes("\0"))throw 0;return x}catch{fail("PORTAL_HTTP_ADAPTER_PATH_INVALID","invalid path")}}
function route(path){if(path==="/snapshot")return["snapshot","portal:snapshot:read","portal:snapshot"];if(path==="/summary")return["summary","portal:summary:read","portal:summary"];if(path==="/records")return["records","portal:records:read","portal:records"];if(path==="/versions")return["versions","portal:versions:read","portal:versions"];const m=path.match(/^\/records\/([^/]+)\/([^/]+)$/);return m?["record","portal:records:read",`portal:records:${seg(m[1])}:${seg(m[2])}`,seg(m[1]),seg(m[2])]:null}
function args(q,r){const commit=one(q,"commit");if(r[0]==="snapshot"||r[0]==="summary")return{commit};if(r[0]==="records")return{commit,institutionalType:one(q,"institutionalType"),offset:integer(q,"offset"),limit:integer(q,"limit")};if(r[0]==="record")return{commit,institutionalType:r[3],institutionalId:r[4]};return{offset:integer(q,"offset"),limit:integer(q,"limit")}}
function call(api,r,a){return r[0]==="snapshot"?api.getSnapshot(a):r[0]==="summary"?api.getSummary(a):r[0]==="records"?api.listRecords(a):r[0]==="record"?api.getRecord(a):api.listVersions(a)}
function code(e){return typeof e?.code==="string"&&(e.code.startsWith("PORTAL_READ_API_")||e.code.startsWith("PORTAL_HTTP_ADAPTER_"))?e.code:"PORTAL_HTTP_ADAPTER_INTERNAL"}
export function createPortalProjectorHttpAdapter({readApi,authenticate,authorize,basePath="/v1/portal"}={}){checkApi(readApi);fn(authenticate,"authenticate");fn(authorize,"authorize");if(typeof basePath!=="string"||!basePath.startsWith("/")||(basePath.length>1&&basePath.endsWith("/")))fail("PORTAL_HTTP_ADAPTER_BASE_PATH_INVALID","invalid basePath");
async function handle(request){let u,method;try{method=String(request?.method??"").toUpperCase();const raw=String(request?.path??request?.url??"");if(!method||!raw.startsWith("/"))throw 0;u=new URL(raw,"http://local")}catch{return err(400,"PORTAL_HTTP_ADAPTER_REQUEST_INVALID","Invalid request")}
if(!u.pathname.startsWith(basePath))return err(404,"PORTAL_HTTP_ADAPTER_ROUTE_NOT_FOUND","Route not found");const p=u.pathname.slice(basePath.length)||"/";if(method!=="GET")return err(405,"PORTAL_HTTP_ADAPTER_METHOD_NOT_ALLOWED","Method not allowed",{allow:"GET"});const r=route(p);if(!r)return err(404,"PORTAL_HTTP_ADAPTER_ROUTE_NOT_FOUND","Route not found");
let id;try{id=await authenticate(Object.fromEntries(Object.entries(request.headers??{}).map(([k,v])=>[k.toLowerCase(),String(v)])),request)}catch{return err(401,"PORTAL_HTTP_ADAPTER_UNAUTHENTICATED","Authentication required")}if(!id)return err(401,"PORTAL_HTTP_ADAPTER_UNAUTHENTICATED","Authentication required");
let ok;try{ok=await authorize(id,{action:r[1],resource:r[2],request})}catch{return err(403,"PORTAL_HTTP_ADAPTER_FORBIDDEN","Access denied")}if(!(ok===true||ok?.allowed===true))return err(403,"PORTAL_HTTP_ADAPTER_FORBIDDEN","Access denied");
try{const data=await call(readApi,r,args(u.searchParams,r));if(data===null)return err(404,"PORTAL_HTTP_ADAPTER_RESOURCE_NOT_FOUND","Resource not found");const mh={};if(typeof data?.sourceCommit==="string")mh["x-source-commit"]=data.sourceCommit;if(typeof data?.contentChecksum==="string")mh.etag=`"sha256-${data.contentChecksum}"`;return res(200,{data},mh)}catch(e){const c=code(e);return c.startsWith("PORTAL_READ_API_")||c.includes("_QUERY_")||c.includes("_PATH_")?err(400,c,"Invalid query"):err(500,"PORTAL_HTTP_ADAPTER_INTERNAL","Internal error")}}
return Object.freeze({handle,basePath,mutationAllowed:false})}
