const BASE="https://developers.hostinger.com";
const req=(v,n)=>{if(typeof v!=="string"||!v.trim())throw new TypeError(`${n} must be non-empty`);return v.trim()};
const domain=v=>req(v,"domain").toLowerCase().replace(/\.$/,"");
const query=(p,o={})=>{const u=new URL(p,"https://x.invalid");for(const[k,v]of Object.entries(o))if(v!==undefined&&v!==null&&v!=="")u.searchParams.set(k,String(v));return u.pathname+u.search};
const collection=p=>Array.isArray(p)?{data:p,meta:null}:Array.isArray(p?.data)?{data:p.data,meta:p.meta??null}:(()=>{throw new HostingerAdapterError("Invalid collection",{code:"invalid_collection"})})();
const installDomain=i=>{for(const v of [i?.domain,i?.site_url,i?.url,i?.home_url])if(typeof v==="string"&&v.trim()){try{return domain(new URL(v).hostname)}catch{return domain(v.replace(/^https?:\/\//,"").split("/")[0])}}return null};
const websiteDomains=w=>[w?.domain,w?.fqdn,...(Array.isArray(w?.domains)?w.domains.flatMap(x=>typeof x==="string"?[x]:[x?.fqdn,x?.domain]):[])].filter(Boolean).map(domain);
const cleanWebsite=w=>Object.freeze({uid:w?.uid??w?.id??null,username:w?.username??w?.user?.username??null,enabled:w?.is_enabled??w?.enabled??w?.state==="active",state:w?.state??null,type:w?.type??w?.vhost_type??null,domains:Object.freeze(websiteDomains(w))});
const cleanInstall=i=>Object.freeze({id:i?.id??i?.software??null,username:i?.username??i?.account_username??null,domain:installDomain(i),path:i?.path??i?.directory??null,version:i?.version??i?.core_version??null,language:i?.language??i?.locale??null,title:i?.title??i?.site_title??null,valid:i?.valid??i?.is_valid??null});
export class HostingerAdapterError extends Error{constructor(message,{code="hostinger_error",status=null,correlationId=null,cause}={}){super(message,{cause});this.name="HostingerAdapterError";this.code=code;this.status=status;this.correlationId=correlationId}}
export class HostingerReadOnlyAdapter{
 #base;#token;#fetch;#timeout;
 constructor({baseUrl=BASE,token,fetchImpl=globalThis.fetch,timeoutMs=15000}={}){this.#base=req(baseUrl,"baseUrl").replace(/\/+$/,"");this.#token=req(token,"token");if(typeof fetchImpl!=="function")throw new TypeError("fetchImpl must be a function");this.#fetch=fetchImpl;this.#timeout=timeoutMs}
 async #get(path){const c=new AbortController(),t=setTimeout(()=>c.abort(),this.#timeout);try{const r=await this.#fetch(this.#base+path,{method:"GET",headers:{accept:"application/json",authorization:`Bearer ${this.#token}`},signal:c.signal});const text=await r.text();let p=null;if(text)try{p=JSON.parse(text)}catch(e){throw new HostingerAdapterError("Invalid JSON",{code:"invalid_json",status:r.status,cause:e})}if(!r.ok)throw new HostingerAdapterError(String(p?.error?.message??p?.message??`HTTP ${r.status}`),{code:"http_error",status:r.status,correlationId:p?.correlation_id??r.headers?.get?.("x-correlation-id")??null});return p}catch(e){if(e instanceof HostingerAdapterError)throw e;throw new HostingerAdapterError(e?.name==="AbortError"?"Request timed out":"Request failed",{code:e?.name==="AbortError"?"timeout":"network_error",cause:e})}finally{clearTimeout(t)}}
 async listWebsites(o={}){const c=collection(await this.#get(query("/api/hosting/v1/websites",{page:o.page??1,per_page:o.perPage??50,username:o.username,order_id:o.orderId,is_enabled:o.isEnabled,domain:o.domain})));return Object.freeze({data:Object.freeze(c.data.map(cleanWebsite)),meta:c.meta})}
 async listWordPressInstallations(o={}){const c=collection(await this.#get(query("/api/hosting/v1/wordpress/installations",{username:o.username,domain:o.domain,ownership:o.ownership})));return Object.freeze({data:Object.freeze(c.data.map(cleanInstall)),meta:c.meta})}
 async getWordPressInstallationJwtToken({username,software}){const p=await this.#get(`/api/hosting/v1/accounts/${encodeURIComponent(req(username,"username"))}/wordpress/${encodeURIComponent(req(software,"software"))}/jwt-token`);const token=p?.token??p?.jwt??p?.access_token;if(!token)throw new HostingerAdapterError("Missing WordPress JWT",{code:"missing_wordpress_jwt"});return Object.freeze({token,expiresIn:Number.isInteger(Number(p?.expires_in))?Number(p.expires_in):null,expiresAt:p?.expires_at??p?.expiration??null,mcpUrl:p?.mcp_url??p?.endpoint??p?.mcp_endpoint??null})}
 async inventoryDomain(value){const d=domain(value),[w,i]=await Promise.all([this.listWebsites({domain:d}),this.listWordPressInstallations({domain:d})]);const websites=w.data.filter(x=>x.domains.includes(d)),installs=i.data.filter(x=>x.domain===d);return Object.freeze({domain:d,websites:Object.freeze(websites),wordpressInstallations:Object.freeze(installs),found:Boolean(websites.length||installs.length),wordpressReady:installs.some(x=>x.valid!==false)})}
}
export const createHostingerReadOnlyAdapter=o=>new HostingerReadOnlyAdapter(o);
