const clone=v=>v==null?v:structuredClone(v);
const str=(v,n)=>{if(typeof v!=="string"||!v.trim())throw new TypeError(`${n} must be a non-empty string`)};
const chk=(ruleId,state,subject,statement,recommendation=null,evidence=[])=>({ruleId,state,subject,statement,recommendation,evidence:[...new Set(evidence.filter(Boolean))].sort()});
const status=c=>c.some(x=>x.state==="fail")?"blocked":c.some(x=>x.state==="unknown")?"needs-evidence":c.some(x=>x.state==="review")?"needs-review":"authorized";
const state=(x,kind)=>{if(!x)return"unknown";if(kind==="constitution"){if(x.effect==="deny"||x.status==="blocked")return"fail";if(x.effect==="allow"||x.status==="compliant")return"pass"}if(kind==="policy"){if(x.effect==="deny")return"fail";if(x.effect==="allow")return"pass"}if(kind==="audit"){if(x.status==="non-compliant")return"fail";if(x.status==="insuffecient-evidence")return"unknown";if(x.status==="attention")return"review";if(x.status==="compliant")return"pass"}if(kind==="evolution"){if(x.status==="blocked-by-evidence")return"unknown";if(x.status==="changes-proposed")return"review";if(x.status==="stable")return"pass"}return"review"};
const approval=a=>{if(!a)return{state:"unknown",failures:[],evidence:[]};const f=[];if(!a.approvalId)f.push("approvalId");if(a.status!=="approved")f.push("status");if(!a.approvedBy)f.push("approvedBy");if(a.replayed===true||a.consumedAt||a.used===true)f.push("replayed");return{state:f.length?"fail":"pass",failures:f,evidence:[a.approvalId].filter(Boolean)}};
const bindings=i=>{const f=[],c=[["approval.tenantId",i.approval?.tenantId,i.tenantId],["approval.decisionId",i.approval?.decisionId,i.decisionId],["approval.proposalId",i.approval?.proposalId,i.proposalId],["constitutionDecision.tenantId",i.constitutionDecision?.tenantId,i.tenantId],["constitutionDecision.decisionId",i.constitutionDecision?.decisionId,i.decisionId],["policyDecision.tenantId",i.policyDecision?.tenantId,i.tenantId],["policyDecision.decisionId",i.policyDecision?.decisionId,i.decisionId],["auditReport.tenantId",i.auditReport?.tenantId,i.tenantId],["auditReport.subject.decisionId",i.auditReport?.subject?.decisionId,i.decisionId],["evolutionReport.sourceAuditId",i.evolutionReport?.sourceAuditId,i.auditReport?.auditId]];for(const[n,a,e]of c)if(a!=null&&e!=null&&a!==e)f.push(n);return f};

export const governanceRules=Object.freeze({GOV001:"constitution compliance",GOV002:"policy authorization",GOV003:"human approval validity and freshness",GOV004:"audit and evidence readiness",GOV005:"evolution readiness and lifecycle binding"});
export const governanceStatuses=Object.freeze(["authorized","needs-review","needs-evidence","blocked"]);

export class GovernanceEngine{
  constructor({clock=()=>new Date().toISOString()}={}){if(typeof clock!=="function")throw new TypeError("clock must be a function");this.clock=clock}
  evaluate({tenantId,decisionId,proposalId,constitutionDecision=null,policyDecision=null,approval:ap=null,auditReport=null,evolutionReport=null}={}, {requestedBy="system",scope="promotion"}={}){
    str(tenantId,"tenantId");str(decisionId,"decisionId");str(proposalId,"proposalId");str(requestedBy,"requestedBy");str(scope,"scope");
    const input={tenantId,decisionId,proposalId,constitutionDecision,policyDecision,approval:ap,auditReport,evolutionReport},before=clone(input),ar=approval(ap),bf=bindings(input);
    const checks=[
      chk("GOV-001",state(constitutionDecision,"constitution"),decisionId,constitutionDecision?"Constitution decision was evaluated.":"No Constitution decision was supplied.",constitutionDecision?null:"Evaluate the governed decision against the active Constitution.",[constitutionDecision?.constitutionDecisionId]),
      chk("GOV-002",state(policyDecision,"policy"),decisionId,policyDecision?"Policy decision was evaluated.":"No Policy decision was supplied.",policyDecision?null:"Evaluate the governed action with kernel-policy.",[policyDecision?.policyDecisionId]),
      chk("GOV-003",ar.state,decisionId,ar.state==="pass"?"Human approval is active and fresh.":ar.state==="unknown"?"No human approval was supplied.":`Human approval is invalid: ${ar.failures.join(", ")}.`,ar.state==="pass"?null:"Supply a fresh explicit approval bound to tenant, decision and proposal.",ar.evidence),
      chk("GOV-004",state(auditReport,"audit"),decisionId,auditReport?`Audit status is ${auditReport.status}.`:"No Audit report was supplied.",auditReport?null:"Run kernel-audit and attach its report.",[auditReport?.auditId,...(auditReport?.evidence??[])]),
      chk("GOV-005",bf.length?"fail":state(evolutionReport,"evolution"),decisionId,bf.length?`Lifecycle binding mismatches: ${bf.join(", ")}.`:evolutionReport?`Evolution status is ${evolutionReport.status}.`:"No Evolution report was supplied.",bf.length?"Rebuild lifecycle artifacts with matching identifiers.":evolutionReport?null:"Run kernel-evolution from the attached Audit report.",[evolutionReport?.evolutionId,evolutionReport?.sourceAuditId])
    ];
    if(JSON.stringify(before)!==JSON.stringify(input))throw new Error("governance input was mutated");
    const st=status(checks),generatedAt=this.clock();
    return{governanceId:`governance.${generatedAt.replace(/[-:.TZ]/g,"").toLowerCase()}`,generatedAt,requestedBy,scope,tenantId,decisionId,proposalId,mode:"authorization-validation",status:st,authorized:st==="authorized",mutationAllowed:false,executionAllowed:false,checks:clone(checks),summary:{total:cachecks.length,pass:checks.filter(x=>x.state==="pass").length,review:checks.filter(x=>x.state==="review").length,fail:checks.filter(x=>x.state==="fail").length,unknown:checks.filter(x=>x.state==="unknown").length},constraints:{denyByDefault:true,humanApprovalRequired:true,constitutionRequired:true,policyRequired:true,auditRequired:true,evolutionRequired:true,executionGatewayRequired:true},references:{constitutionDecisionId:constitutionDecision?.constitutionDecisionId??null,policyDecisionId:policyDecision?.policyDecisionId??null,approvalId:ap?.approvalId??null,auditId:auditReport?.auditId??null,evolutionId:evolutionReport?.evolutionId??null}}
  }
}
export const createGovernanceEngine=(options={})=>new GovernanceEngine(options);
