import{createHash}from"node:crypto";
const req=(v,n)=>{if(typeof v!=="string"||!v.trim())throw new TypeError(`${n} must be non-empty`);return v.trim()};
const base=v=>{const u=new URL(req(v,"baseUrl"));if(!/^https?:$/.test(u.protocol))throw new TypeError("baseUrl must use HTTP(S)");return u.href.replace(/\/+$/,"")};
const slug=v=>req(v,"slug").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const text=v=>String(v??"").replace(/\r\n/g,"\n").trim();
const title=p=>typeof p?.title==="string"?p.title:p?.title?.raw??p?.title?.rendered??"";
const content=p=>typeof p?.content==="string"?p.content:p?.content?.raw??p?.content?.rendered??"";
const fp=v=>({sha256:createHash("sha256").update(text(v)).digest("hex"),bytes:Buffer.byteLength(text(v),"utf8")});
const authHeader=a=>!a?null:a.type==="bearer"?`Bearer ${req(a.token,"auth.token")}`:a.type==="application-password"?`Basic ${Buffer.from(`${req(a.username,"auth.username")}:${req(a.applicationPassword,"auth.applicationPassword")}`).toString("base64")}`:(()=>{throw new TypeError("Unsupported auth type")})();
export class WordPressAdapterError extends Error{constructor(message,{code="wordpress_error",status=null,cause}={}){super(message,{cause});this.name="WordPressAdapterError";this.code=code;this.status=status}}
export class WordPressReadOnlyAdapter{
 #base;#auth;#fetch;#timeout;
 constructor({baseUrl,auth=null,fetchImpl=globalThis.fetch,timeoutMs=15000}={}){this.#base=base(baseUrl);this.#auth=authHeader(auth);if(typeof fetchImpl!=="function")throw new TypeError("fetchImpl must be a function");this.#fetch=fetchImpl;this.#timeout=timeoutMs}
 async #get(path,secured=false){if(secured&&!this.#auth)throw new WordPressAdapterError("Authentication not configured",{code:"authentication_not_configured"});const c=new AbortController(),t=setTimeout(()=>c.abort(),this.#timeout),headers={accept:"application/json"};if(secured)headers.authorization=this.#auth;try{const r=await this.#fetch(this.#base+path,{method:"GET",headers,signal:c.signal});const raw=await r.text();let p=null;if(raw)try{p=JSON.parse(raw)}catch(e){throw new WordPressAdapterError("Invalid JSON",{code:"invalid_json",status:r.status,cause:e})}if(!r.ok)throw new WordPressAdapterError(String(p?.message??`HTTP ${r.status}`),{code:p?.code??"http_error",status:r.status});return{payload:p,total:Number(r.headers?.get?.("x-wp-total")??0),totalPages:Number(r.headers?.get?.("x-wp-totalpages")??0)}}finally{clearTimeout(t)}}
 async discover(){const{payload:p}=await this.#get("/wp-json/");const ns=Array.isArray(p?.namespaces)?p.namespaces:[],routes=p?.routes??{};return Object.freeze({name:p?.name??null,url:p?.url??this.#base,hasWpV2:ns.includes("wp/v2")||Boolean(routes["/wp/v2"]),hasPagesRoute:Boolean(routes["/wp/v2/pages"])})}
 async validateAuthentication(){const{payload:p}=await this.#get("/wp-json/wp/v2/users/me?context=edit&_fields=id,slug,name,roles,capabilities",true);return Object.freeze({validated:true,user:Object.freeze({id:p?.id??null,slug:p?.slug??null,name:p?.name??null,roles:Object.freeze(Array.isArray(p?.roles)?p.roles:[]),canEditPages:Boolean(p?.capabilities?.edit_pages??p?.capabilities?.manage_options),canPublishPages:Boolean(p?.capabilities?.publish_pages??p?.capabilities?.manage_options)})})}
 async listPages(){const fields=encodeURIComponent("id,slug,status,title,content,template,menu_order,modified_gmt,link");const{payload:p,total,totalPages}=await this.#get(`/wp-json/wp/v2/pages?context=edit&per_page=100&orderby=id&order=asc&_fields=${fields}`,true);if(!Array.isArray(p))throw new WordPressAdapterError("Invalid pages response",{code:"invalid_pages_response"});return Object.freeze({data:Object.freeze(p.map(x=>Object.freeze({id:x.id,slug:x.slug,status:x.status,title:title(x),content:content(x),template:x.template??null,menuOrder:x.menu_order??0,modifiedGmt:x.modified_gmt??null,link:x.link??null}))),total,totalPages})}
 planPages(desired,existing){if(!Array.isArray(desired)||!Array.isArray(existing))throw new TypeError("Page inputs must be arrays");const bySlug=new Map(existing.filter(x=>x?.slug).map(x=>[slug(x.slug),x]));const seen=new Set();const operations=desired.map((x,i)=>{const target=Object.freeze({slug:slug(x.slug??x.title),title:req(x.title,`pages[${i}].title`),status:x.status??"draft",contentFingerprint:fp(x.content),template:x.template??null,menuOrder:Number.isInteger(x.menuOrder)?x.menuOrder:0});if(seen.has(target.slug))throw new TypeError(`duplicate desired page slug: ${target.slug}`);seen.add(target.slug);const cur=bySlug.get(target.slug);if(!cur)return Object.freeze({action:"create",slug:target.slug,target,current:null,reasons:Object.freeze(["missing_page"])});const current=Object.freeze({id:cur.id??null,slug:cur.slug,title:title(cur),status:cur.status??null,contentFingerprint:fp(content(cur)),template:cur.template??null,menuOrder:cur.menuOrder??cur.menu_order??0,link:cur.link??null});const reasons=[];if(text(current.title)!==target.title)reasons.push("title_changed");if(current.status!==target.status)reasons.push("status_changed");if(current.contentFingerprint.sha256!==target.contentFingerprint.sha256)reasons.push("content_changed");if(current.template!==target.template)reasons.push("template_changed");if(current.menuOrder!==target.menuOrder)reasons.push("menu_order_changed");return Object.freeze({action:reasons.length?"update":"noop",slug:target.slug,target,current,reasons:Object.freeze(reasons)})});return Object.freeze({mode:"dry-run",writesEnabled:false,operations:Object.freeze(operations),totals:Object.freeze({create:operations.filter(x=>x.action==="create").length,update:operations.filter(x=>x.action==="update").length,noop:operations.filter(x=>x.action==="noop").length})})}
}
export const createWordPressReadOnlyAdapter=o=>new WordPressReadOnlyAdapter(o);
